### ISSUE TITLE
Waveform Morph

### ISSUE THREAD

**Issue by cornelisser** [cornelisser/TriloTracker#110]
- Implement as state based (e.g. do not stop when note is played). 
- Add effect to set higher bank?
- Review workings. Perhaps we can do this in nicer way (effect options wise).

**Comment by artrag** [comment]
Hi Richard,
I think I've proposed you something about this already, what about adding the possibility to change waveforms at each frame according to a sequence of pre-computed data and periods? You could mimic a longer sample on multiple frames obtained by the concatenation of multiple waves.
Using a close derivative of the algorithm used for voice encoding I can approximate a sample from a real instrument as a sequence of SCC periods and waveforms of 32 samples. The approximation will be a band limited version of the original and can work better for certain sounds (those with periodic shape) than for others, but generally it is worth a try. By dividing the sequence of periods by multiples of 2^(1/12) you can make the sample play any note, but I think you have already done something like this while playing SCC waves.
Let me know
AR
PS
You can see how looks like current data from here
https://github.com/artrag/voicenc_scc/tree/master/data
Look for all_data_files_periods.asm and all_data_files_waves.asm
They are used in the ROM sccLOFI_1c.rom in the same repository

**Comment by cornelisser** [comment]
Hi Arturo!

This is still something that is in my try list. The issue with this is that I need quite some work to free the needed RAM.

I also want to add the lofi samples for PSG/Fm that you Made. 
The idea is that I will try to free up 8kb for such experiments.

But first I need to finish the New replayer.

Anyway, how is Life? 
Good to hear from you.

Regards,
Richard

Verstuurd vanaf mijn iPhone

**Comment by artrag** [comment]
Nice to hear from you as well! Looking at what GhostwriterP has achieved using SCC I think that integrating voicenc_scc is the best way to proceed. Samples from LoFi PSG sound very poor compared to  voicenc_scc and with this latter on SCC you can play up to one sample per channel. Let me know when you are ready!
I eager to see what we can get!
AR

**Comment by cornelisser** [comment]
Hi,

I know SCC will sound much better. But still. You work on PSG and tests on
FM has some kind of charm. I think with a little trick we can even create a
better HW voice to use for playback to improve playback. On Sega Master
System there is no SCC so the lofi is the next best thing.
I will try to make time to free the needed RAM to do tests.

Regards,
Richard

Op di 1 sep. 2020 om 22:53 schreef artrag <notifications@github.com>:

**Comment by Gryzor87** [comment]
Hi there Richard and Artrag,
Please sorry for using this thread to contact you. I am involved in a new and exciting project (Some MoG sequel) and using the last TT you gave me (V 0.10.0?, with new syntax commands), but cannot find the proper replayer and compiler, and have done several test with Replayer V0.3.1 with crashes and sound issues :(
I would really appreciate some help...
Thanks very much in advance
Best Regards,
Javier

**Comment by cornelisser** [comment]
Re-implemented Morph

**Comment by cornelisser** [comment]
Hi Arturo,

How are you? Hope you and your family is safe.

I have finished most work on the trackers. I am ready to experiment with
lo-fi SCC samples.
I will incorporate the example routine and data, you shared, in to the
tracker.

Did you also experiment with 'normal' sampling using 1 channel. If I am
correct that would be at 1,6Khz (50hz) or 1,92Khz (60Hz). Right?
I'm wondering how they compare to each other. when used in music.

Regards,
Richard


Op di 1 sep. 2020 om 22:53 schreef artrag <notifications@github.com>:
