### ISSUE TITLE
0.9.2 and 0.9.1 - no sound with FM-PAQ

### ISSUE THREAD

**Issue by drakonia667** [cornelisser/TriloTracker#124]
Trilo Tracker and FM-PAQ. After loading the song, there is a silence in the air (both on FM and PSG channels). Moonblaster 1.4 plays all FM channels correctly, so FM-PAQ is working. I changed the SCC Slot settings to all possible sequences (FM-PAQ is plugged into the rear VG-8235 port).
Version 0.9.2 - silence.
Version 0.9.1 - silence.
Version 0.9.0 - all OK.

I run TT from FMR SCC not from a floppy disk image, but directly from a folder, if relevant.

**Comment by cornelisser** [comment]
Hi, 
I will contact you next week to help you with your issues. 

Regards,
Richard

**Comment by cornelisser** [comment]
The versions available on the website seem to be not working correctly. 
These are quite some old versions and in the mean time a lot of work is gone in a newer version. I will try to make the new versions available for beta testing this week.

Hope this will help.
