### ISSUE TITLE
Cannot compile from sources

### ISSUE THREAD

**Issue by santiontanon** [cornelisser/TriloTracker#125]
Hi, I was trying to recompile TriloTracker from sources, but I cannot figure it out. There seems to be several main files (ttracker.asm, ttrackerEPSG.asm, etc.), some of them include files that are not in the repo (happy to give you the exact files if needed). Trying to compile ttracker.asm, for example, fails because the function "processkey_drumeditor", is not included in this version. Any help would be appreciated! thanks in advance! :)

**Comment by cornelisser** [comment]
Thanks!

I'm back from holiday and will pick this up asap.

**Comment by cornelisser** [comment]
Removed faulty files (like ttrackerPSG) that will not compile. Remaining files (ttrackerSCC.asm, ttrackerFM and ttrackerSMS) will nog compiled without issues.

**Comment by santiontanon** [comment]
Great! thanks!!!

**Comment by santiontanon** [comment]
Apologies for responding to a closed issue, but I seem to not be able to compile from sources again. I just do "sjasm ttrackerSCC.asm" and I get "ttrackerSCC.asm(20) : Part 'MAIN' does not fit in page 0". I tried using the "-j" flag of sjasm to see if that had anything to do, but no luck either. I am using sjasm v0.42c, is that the right version? Just wondering what am I doing wrong haha. Thanks in advance!

**Comment by cornelisser** [comment]
No problem. I'll try to see what is going on asap.

**Comment by cornelisser** [comment]
I just downloaded a zip of the current code on Github. I've extracted all into a new folder and compiled (`sjasm trackerSCC.asm TTSCC.COM` )with sjasm v0.42b8. I did not have any issues. 

![image](https://user-images.githubusercontent.com/9334373/109433478-c51cda80-7a10-11eb-8fa1-f4d203e1e971.png)

Will try with the sjasm v0.42c.

**Comment by cornelisser** [comment]
It seems that the newer version of sjasm handles `jr.` differently.
![image](https://user-images.githubusercontent.com/9334373/109434399-6574fe00-7a15-11eb-93f6-0d316827829a.png)

I'm not sure if this is a bug in sjasm or if this is intentional.

**Comment by santiontanon** [comment]
Oh, interesting! I'll use 0.42b8 in the meantime. But from that screenshot, one possible explanation is that the algorithm to allocate blocks to pages has slightly changed from one version of sjasm to the other, which makes that "jr." become a jp in one version and a jr in the other, since maybe the target block has been placed farther in one case than the other. Very curious!

**Comment by cornelisser** [comment]
Anyway. I'll add a not to the repository to not use version v0.42c

**Comment by cornelisser** [comment]
I have restructured the memory layout. Making page 0 smaller. Now the issue probably won't happen.
Still need to check after other prio's are finished.
