### ISSUE TITLE
Implement Sample loading and editing.

### ISSUE THREAD

**Issue by cornelisser** [cornelisser/TriloTracker#133]
Under F3 we can place the sample editor. 

- Loads TSU files (created with TSU compiler from wavs).
- Save TSU files
- Save PAK files (samplepak)
- Load PAK files

Edit the following:
- Base note
- Restart offset
- Length/start (not saved, will crop the sample when saved)

Are we going to store the names?

**Comment by artrag** [comment]
Maybe the sample name could be the name of the TSU file itself, as now TSU file has a single sample

**Comment by cornelisser** [comment]
Good idea. That was what I was thinking too.

**Comment by cornelisser** [comment]
Loading works. Memory management (on deleting/overwriting samples is in place.

Next steps:
- Save/load sample pak.
- Do not save sample data in TMU file.
- Edit sample data (base note, and offsets; start, end, loop)
- Save samples
- Commit offsets (to clean up unused RAM)

I will implement them in separate stories
