### ISSUE TITLE
SCC Sample encoder - Stand-alone version

### ISSUE THREAD

**Issue by artrag** [cornelisser/TriloTracker#146]
This is a compiled version of the sample encoder for windows command line 

[voicenc_scc.zip](https://github.com/cornelisser/TriloTracker/files/6098062/voicenc_scc.zip)

Instructions for installing its libraries are in readme.txt
Once installed create a \wavs directory for storing input wav  files and a \data for results
use -p to play the processed file while encoding
Use -50 to encode for PAL or -60 for NTSC samples

**Comment by artrag** [comment]
I have spotted a bug in parsing the command line parameters. Only one parameter at time now is accepted (or Hz or playback)...
I will send you a fix asap

**Comment by artrag** [comment]
This time command line should be ok

[tt_voicenc_scc_2021_03_12.zip](https://github.com/cornelisser/TriloTracker/files/6133352/tt_voicenc_scc_2021_03_12.zip)

**Comment by artrag** [comment]
I've added more parameters aimed to encoding instruments and non vocal sounds
In the command line you can use:
tnn
where nn is a two digit integer in 0-99  you can change the threshold used to commute from vocal segments to unvoiced segments 
nn=00 means that all the sample is processed as voiced using the estimated pitch 
nn=99 means that all the sample is processed as unvoiced using the frequency peak as base frequency

You can also use 
gmmmmm
Where mmmmm is a 5 digits number representing the SCC period.
This parameter is used to force the pitch used in the waveform approximation to a known values
It is useful for sampling instruments where the note played by the sample is known
 



[tt_voicenc_scc_2021_03_23.zip](https://github.com/cornelisser/TriloTracker/files/6185847/tt_voicenc_scc_2021_03_23.zip)

**Comment by artrag** [comment]
I've implemented a new encoder able to optimise the phase of wave samples to reduce discontinuity between frames
Let me know how it goes
https://github.com/artrag/voicenc_scc/releases

No changes in the format of the .SAM files

**Comment by cornelisser** [comment]
Great work! Thanks for the effort. This feature is getting better and better.
