### ISSUE TITLE
Inputting a particular order of Cxx effects hangs the program

### ISSUE THREAD

**Issue by TastySnax12** [cornelisser/TriloTracker#199]
![IMG_20220302_202814218_HDR](https://user-images.githubusercontent.com/73725977/156478772-53f53867-9b0e-4dfb-8771-c573ece4adcc.jpg)

**Comment by cornelisser** [comment]
Hi,

Thanks for your feedback. I will look at the issue asap. 

Regards, Richard 

Verstuurd vanaf mijn iPhone

**Comment by cornelisser** [comment]
I tested the same scenario but unable to reproduce. 
I tested on:
- openMSX
- real MSX turbo-R (R800 mode)
- real MSX turbo-R (Z80 mode)

Will do some extra testing later

**Comment by cornelisser** [comment]
Unable to reproduce this issue.
