### ISSUE TITLE
Pattern corruption when using orDer

### ISSUE THREAD

**Issue by jelonertz** [cornelisser/TriloTracker#205]
I've found that when I use CTRL+D to manage the patterns, some of them get corrupted with garbage. I'm using TTSCC v0.11.9 in OpenMSX loaded from a MFRSCC+ SD.

![image](https://user-images.githubusercontent.com/30060886/181880282-b5f2e2ff-2a4e-4b4e-a7e0-b77e1591ef9d.png)

**Comment by cornelisser** [comment]
Thanks for the report. 
I will try to reproduce and fix the issue.

**Comment by jelonertz** [comment]
Hi,

Is there a way to disable the loop [R] function in version 0.11.9?

Thanks!

**Comment by cornelisser** [comment]
Disabling the loop is not implemented. 
There is a feature pending for this. Not sure when I will be able to implement this.

**Comment by cornelisser** [comment]
For the next release looping is optional for the song order and instruments.

**Comment by jelonertz** [comment]
Awesome! Thanks!

**Comment by cornelisser** [comment]
The repeat is now optional in the latest release.
